// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripPlanner.Infrastructure.Data;

#nullable disable

namespace TripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(TripPlannerDbContext))]
    partial class TripPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripPlanner.Domain.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("destination_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("destinations", (string)null);

                    b.HasDiscriminator<string>("destination_type").HasValue("Destination");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.TripDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Day")
                        .IsUnique();

                    b.ToTable("trip_days", (string)null);
                });

            modelBuilder.Entity("trip_day_destinations", b =>
                {
                    b.Property<int>("trip_day_id")
                        .HasColumnType("integer");

                    b.Property<int>("destination_id")
                        .HasColumnType("integer");

                    b.HasKey("trip_day_id", "destination_id");

                    b.HasIndex("destination_id");

                    b.ToTable("trip_day_destinations", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.Landmark", b =>
                {
                    b.HasBaseType("TripPlanner.Domain.Models.Destination");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasDiscriminator().HasValue("Landmark");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Landmark 81",
                            Rating = 4.5,
                            destination_type = "Landmark",
                            OpeningHours = "08:00 - 22:00"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hoi An Ancient Town",
                            Rating = 4.7999999999999998,
                            destination_type = "Landmark",
                            OpeningHours = "Open all day"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vinpearl Safari Phu Quoc",
                            Rating = 4.5999999999999996,
                            destination_type = "Landmark",
                            OpeningHours = "09:00 - 16:00"
                        });
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.Restaurant", b =>
                {
                    b.HasBaseType("TripPlanner.Domain.Models.Destination");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsHalalFriendly")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Name = "Com que duong bau",
                            Rating = 4.4000000000000004,
                            destination_type = "Restaurant",
                            CuisineType = "Vietnamese",
                            IsHalalFriendly = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pho Hoa Pasteur",
                            Rating = 4.5,
                            destination_type = "Restaurant",
                            CuisineType = "Vietnamese",
                            IsHalalFriendly = false
                        },
                        new
                        {
                            Id = 6,
                            Name = "Com tam 3 anh em",
                            Rating = 4.4000000000000004,
                            destination_type = "Restaurant",
                            CuisineType = "Vietnamese",
                            IsHalalFriendly = false
                        });
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.TripDay", b =>
                {
                    b.HasOne("TripPlanner.Domain.Models.Trip", null)
                        .WithMany("Days")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("trip_day_destinations", b =>
                {
                    b.HasOne("TripPlanner.Domain.Models.Destination", null)
                        .WithMany()
                        .HasForeignKey("destination_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Domain.Models.TripDay", null)
                        .WithMany()
                        .HasForeignKey("trip_day_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Domain.Models.Trip", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
